package com.revature.controller;



	public class ExceptionController {

		public void mapExceptions(Javalin app) {
			app.exception(FailedLoginException.class, (e, ctx) -> {
				ctx.status(400);
				ctx.json(new MessageDTO(e.getMessage()));
			});
			
			app.exception(UnauthorizedException.class, (e, ctx) -> {
				ctx.status(401);
				ctx.json(new MessageDTO(e.getMessage()));
			});
			
			app.exception(ReimbursementNotFoundException.class, (e, ctx) -> {
				ctx.status(404);
				ctx.json(new MessageDTO(e.getMessage()));
			});
			
			app.exception(InvalidParameterException.class, (e, ctx) -> {
				ctx.status(400);
				ctx.json(new MessageDTO(e.getMessage()));
			});
			
			app.exception(ReimbursementAlreadyResolvedException.class, (e, ctx) -> {
				ctx.status(400);
				ctx.json(new MessageDTO(e.getMessage()));
			});
			
			app.exception(ReceiptNotFoundException.class, (e, ctx) -> {
				ctx.status(404);
				ctx.json(new MessageDTO(e.getMessage()));
			});
		}
		
	}
	
}